POST request for salesman done2
Funtikl/companyREST pull request #2
Opened 2021-08-25 18:13 UTC by Funtikl

2021-08-26 08:32 UTC, Funtikl commented
Hello

2021-08-26 08:58 UTC, Lomo89 commented
Oh crap, I lost my comments :D Will do it again.

2021-08-26 09:00 UTC, Funtikl commented
OK, I see now :)

2021-08-26 09:04 UTC, Lomo89 requested changes

2021-08-26 09:04 UTC, Lomo89 commented on app.py
> +api.add_resource(BooksRes, '/books/<string:name>')
Let's add each resource on its own file. 
Also, the pattern to follow when naming endpoints is: version/appname/resource, so in this case it would be:
`/v1/company/book/<string:name>`

2021-08-26 09:04 UTC, Lomo89 commented on app.py
>      app.run(port=5000, debug=True)
Out of curiosity, why the port 5000?

2021-08-26 09:04 UTC, Lomo89 commented on resources/books.py
> +        return {'message': 'Book not found'}
not found has code 404, let's add it

2021-08-26 09:04 UTC, Lomo89 commented on resources/books.py
> +            return {"message":"Error"}
Let's provide more info on the error:

```
        try:
            book.save_to_db()
        except Exception as ex:
            return {"message": f"Error: {str(ex)}"}
```

2021-08-26 09:04 UTC, Lomo89 commented on resources/books.py
> +        return {"message":"Book {} not found".format(name)}
notfound code= 404

2021-08-26 09:07 UTC, Funtikl commented
Oh, you commented it. Thank you. Now I will try to understand what is going on :)

2021-08-26 09:09 UTC, Funtikl commented on app.py
>      app.run(port=5000, debug=True)
I saw it in one tutorial and think that it matters :)

2021-08-26 09:09 UTC, Lomo89 commented on app.py
>      app.run(port=5000, debug=True)
Usually on my company all the apps use 8000, but 5000 is ok too :)

2021-08-26 09:15 UTC, Funtikl commented on app.py
> +api.add_resource(BooksRes, '/books/<string:name>')
You mean, to import api to resources files and do : api.add_resource() - there?

2021-08-26 09:18 UTC, Lomo89 commented
I've seen you ask about how to debug the app but I don't see the comment anymore, so here it goes:
You need to add a logger. To do that you need to import it on each file. Now, im not sure how it was done, so I'll  give you 2 options.

- Option 1.
 first import the logger -> `import logging`
 Then initialize it -> ```logging.basicConfig()
                                   logger = logging.getLogger(__name__)```
And then just use it whenever you want -> `logger.debug(message)`
- Option 2:
 import same as above and then add the config (You might need to add it on each file)
 ```logging.basicConfig(
level=logging.INFO,
format="%(asctime)s [%(levelname)s] %(message)s",
handlers=[
logging.FileHandler("debug.log"),
logging.StreamHandler()
]
)```
Then get the logger as before `logger = logging.getLogger(__name__)` and use it same as before.

Then you should see log messages.

2021-08-26 09:18 UTC, Funtikl commented
I changed everything but the first. 
Do you see what cause the issue in BooksModel or BookRes that it cannot write data to DB?

2021-08-26 09:19 UTC, Funtikl commented
> I've seen you ask about how to debug the app but I don't see the comment anymore, so here it goes:
> You need to add a logger. To do that you need to import it on each file. Now, im not sure how it was done, so I'll give you 2 options.
> 
>     * Option 1.
>       first import the logger -> `import logging`
>       Then initialize it -> `logging.basicConfig() logger = logging.getLogger(__name__)`
>       And then just use it whenever you want -> `logger.debug(message)`
> 
>     * Option 2:
>       import same as above and then add the config (You might need to add it on each file)
> 
> 
> ```
> level=logging.INFO,
> format="%(asctime)s [%(levelname)s] %(message)s",
> handlers=[
> logging.FileHandler("debug.log"),
> logging.StreamHandler()
> ]
> )```
> Then get the logger as before `logger = logging.getLogger(__name__)` and use it same as before.
> 
> Then you should see log messages.
> ```

Thank you!

2021-08-26 09:23 UTC, Lomo89 commented on app.py
> +api.add_resource(BooksRes, '/books/<string:name>')
No. Make a file per resource, in this case books.py and then you do 1 method per request type (GET, POST, DELETE, etc)
Then you use the decorator and add the endpoint there. Something like this:
```
@app.route("/v1/company/book/<string:name>", methods=["GET"])
def get_book():
  # here add the logic to fetch the book
```
So then each resource or Db table will have is own file (1 for books,  1 for salesman, etc...)

2021-08-26 09:27 UTC, Lomo89 commented on models/books.py
> +class BooksModel(db.Model):
it's a mode for a single book, please rename to BookModel

2021-08-26 09:27 UTC, Lomo89 commented
> I changed everything but the first.
> Do you see what cause the issue in BooksModel or BookRes that it cannot write data to DB?

Do we have any error message for that issue?

2021-08-26 09:32 UTC, Funtikl commented on models/books.py
> +class BooksModel(db.Model):
Done

2021-08-26 09:34 UTC, Funtikl commented
> > I changed everything but the first.
> > Do you see what cause the issue in BooksModel or BookRes that it cannot write data to DB?
> 
> Do we have any error message for that issue?

When I try to GET: 
def get(self, name):
        book = BookModel.find_by_name(name)
        if book:
            return book.json()
        return {'message': 'Book not found'}, 404    

And when I try to POST:
   try:
            book.save_to_db()
        except Exception as ex:
            return {"message": f"Error: {str(ex)}"}, 404
        return book.json(), 201
When I POST, it doesn't give me an error. After, When I make GET request, It returns "Book not found"

2021-08-26 09:52 UTC, Funtikl commented on app.py
> +api.add_resource(BooksRes, '/books/<string:name>')
Github doesn't show this? I have done this already. Or maybe we are talking about different things. FlaskRestful makes it with Resources and Api classes on its own. I created Resources folder and create books.py, salesman.py and etc. Instade of @app.route decorator, flask restfull makes it with classes.
If I have to do with flask decorator, then I have to delete flaskRestful. I am confused :)

2021-08-26 10:40 UTC, Funtikl commented
There is a variable "data" In BookRes class in the "post" method. I printed it. It works correctly. Below "data" variable, there is "book" variable. I store in it BookModel(**data). Then, I try to save it to db. I think, the problem is here. In Salesman file, everything is identical but there it works. Here it doesn't and I don't know why. 
I try to solve it now

2021-08-26 12:24 UTC, Funtikl commented
I used sqlite shell. Data what I am posting is there. Problem is in GET method.

2021-08-26 12:26 UTC, Funtikl commented
It was a problem with case sensetivity. It works. Oh god. Sorry for many messages and taking your time.

2021-08-27 07:20 UTC, Lomo89 approved these changes
the code looks good, just check that all return statments have the respective code. I see some are missing.

2021-08-27 07:20 UTC, Lomo89 commented on app.py
> +api.add_resource(BooksRes, '/books/<string:name>')
What I'm trying to say is that each endpoint should be on it's own file, not all on this one.

2021-08-27 07:20 UTC, Lomo89 commented on resources/books.py
> +class BooksRes(Resource):
`BookResource` it a short name, no need to make it shorter :)

2021-08-27 07:20 UTC, Lomo89 commented on resources/books.py
> +            return {"message": f"Error: {str(ex)}"}, 404
this is not a 404. 404 means not found, here something went wrong while saving and you don't know what, so most probably is a 500 error

2021-08-27 11:32 UTC, Funtikl commented on resources/books.py
> +class BooksRes(Resource):
Ok :) I corrected it 👍

2021-08-27 11:33 UTC, Funtikl commented on resources/books.py
> +            return {"message": f"Error: {str(ex)}"}, 404
I will learn all codes :)

2021-08-27 11:38 UTC, Funtikl commented
1) I have a problem with this:
`api.add_resource(BooksRes, '/books/<string:name>')`
I tried to improt api from app.py to resources/books.py but it didn't work.
2) Do I have to create html templates now? Is this right way to do it: ⬇️
Create templates folder -> index.html -> html files for books, salesmen and stores to submit form and show content.

2021-08-28 15:08 UTC, alatasma commented
> 1) I have a problem with this:
> `api.add_resource(BooksRes, '/books/<string:name>')`
> I tried to improt api from app.py to resources/books.py but it didn't work.
> 2) Do I have to create html templates now? Is this right way to do it: ⬇️
> Create templates folder -> index.html -> html files for books, salesmen and stores to submit form and show content.

Regarding the first point, I'll check it on Monday with the computer.
Second point is more front end on which I'm not an expert at all.

2021-08-28 18:26 UTC, Funtikl commented
Hello. Do you mean that I can work as a backend developer without coding frontend at all? It is very good news! :) I hate frontend :) 
Thank you and wish you a good time!

2021-08-29 08:49 UTC, alatasma commented
Yes, I mean exactly that. Coding backend and frontend would make you a full stack developer

2021-08-30 16:02 UTC, Funtikl commented
Hello. How are you? 🙂 
What do you think, I have to make something with this project else or I have to create new project with other framework or something else ?

2021-09-04 17:12 UTC, merged